name: 24/7 Kick to YT & Restream Broadcast

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  broadcaster:
    runs-on: ubuntu-latest

    steps:
      - name: جلب ملفات المستودع
        uses: actions/checkout@v3

      - name: تثبيت FFmpeg و Streamlink
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip3 install streamlink

      - name: تشغيل سكربت البث المباشر
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x stream.sh
          ./stream.sh
